Traceback (most recent call last):
  File "/mnt/lustre/work/geiger/gwb345/LLMCBench/evaluate_mmlu.py", line 140, in <module>
    main(args)
  File "/mnt/lustre/work/geiger/gwb345/LLMCBench/evaluate_mmlu.py", line 94, in main
    model = AutoModelForCausalLM.from_pretrained(args.path, device_map="auto",trust_remote_code=True)
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/transformers/modeling_utils.py", line 309, in _wrapper
    return func(*args, **kwargs)
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4285, in from_pretrained
    raise ValueError(
ValueError: Using a `device_map`, `tp_plan`, `torch.device` context manager or setting `torch.set_default_device(device)` requires `accelerate`. You can install it with `pip install accelerate`
srun: error: galvani-cn222: task 0: Exited with exit code 1
srun: Terminating StepId=1525446.0
