Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:07,  2.52s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:06<00:06,  3.09s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:08<00:02,  2.85s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:09<00:00,  1.92s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:09<00:00,  2.26s/it]
Traceback (most recent call last):
  File "/mnt/lustre/work/geiger/gwb345/LLMCBench/evaluate_PIQA.py", line 109, in <module>
    main(args)
  File "/mnt/lustre/work/geiger/gwb345/LLMCBench/evaluate_PIQA.py", line 76, in main
    df = load_piqa_df(split)
  File "/mnt/lustre/work/geiger/gwb345/LLMCBench/evaluate_PIQA.py", line 17, in load_piqa_df
    ds = load_dataset("piqa", split=split)
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/datasets/load.py", line 2062, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/datasets/load.py", line 1782, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/datasets/load.py", line 1664, in dataset_module_factory
    raise e1 from None
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/datasets/load.py", line 1614, in dataset_module_factory
    ).get_module()
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/datasets/load.py", line 1264, in get_module
    trust_remote_code = resolve_trust_remote_code(self.trust_remote_code, self.name)
  File "/home/geiger/gwb345/miniconda/envs/thesis/lib/python3.10/site-packages/datasets/load.py", line 137, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for piqa contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/piqa.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.
srun: error: galvani-cn208: task 0: Exited with exit code 1
srun: Terminating StepId=1526733.0
